[system]
port = ":7788"
host = "127.0.0.1"

[crmeb_config]
version = "CRMEB-GO-V1.0.0" # 当前代码版本
domain = "" #配合swagger使用 # 待部署域名
wechat_api_url = "" #请求微信接口中专服务器
wechat_js_api_debug = false #微信js api系列是否开启调试模式
wechat_js_api_beta = true #微信js api是否是beta版本
async_config = false #是否同步config表数据到redis
async_wechat_program_temp_list = false #是否同步小程序公共模板库
image_path = "D:\\goproject\\xxfasu\\crmeb_go\\crmebimage\\" # 服务器图片路径配置 斜杠结尾

[mysql]
source = "root:password@tcp(127.0.0.1:3306)/crmeb?charset=utf8mb4&parseTime=True&loc=Local"

[redis]
addr = "127.0.0.1:6379"
username = ""
password = ""
db = 0
use_cluster = false
cluster_addrs = [""]

[oss]
provider = "aliyun"

[aliyun_oss]
endpoint = ""
key_id = ""
key_secret = ""
bucket = ""
region = ""
role_arn = ""
domain = ""

[qiniuyun_oss]
access_key = ""
secret_key = ""
bucket = ""
zone = ""

[zap_log]
log_level = "debug"
encoding = "console"  # json or console
log_file_name = "./storage/logs/server.log"
max_backups = 30
max_age = 7
max_size = 1024
compress = true
